spring.application.name=Guardrails

spring.datasource.url=jdbc:postgresql://localhost:5432/guardrails
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

# Shows Spring's transaction boundary events (Begin, Commit, Rollback)
logging.level.org.springframework.transaction=DEBUG
logging.level.org.springframework.orm.jpa.JpaTransactionManager=DEBUG

# (Optional) Shows Hibernate's internal transaction handling
logging.level.org.hibernate.engine.transaction.internal.TransactionImpl=DEBUG